"""drop unused assets.department_id (never synced, filter via active allocation join instead)

Revision ID: 32bc8f422613
Revises: 4ea336edc49d
Create Date: 2026-07-12 11:09:38.466574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32bc8f422613'
down_revision: Union[str, Sequence[str], None] = '4ea336edc49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assets_ibfk_3'), 'assets', type_='foreignkey')
    op.drop_column('assets', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('department_id', mysql.CHAR(length=32), nullable=True))
    op.create_foreign_key(op.f('assets_ibfk_3'), 'assets', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
