"""add audit_cycles and audit_items tables

Revision ID: 32c9d23c3593
Revises: 474a2352c325
Create Date: 2026-07-12 10:37:20.687475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c9d23c3593'
down_revision: Union[str, Sequence[str], None] = '474a2352c325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_cycles',
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('auditor_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='audit_cycle_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('utc_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('utc_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_items',
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('expected_location', sa.String(length=255), nullable=True),
    sa.Column('verification', sa.Enum('VERIFIED', 'MISSING', 'DAMAGED', name='audit_verification', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('utc_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('utc_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cycle_id'], ['audit_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_items_asset_id'), 'audit_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_audit_items_cycle_id'), 'audit_items', ['cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_items_cycle_id'), table_name='audit_items')
    op.drop_index(op.f('ix_audit_items_asset_id'), table_name='audit_items')
    op.drop_table('audit_items')
    op.drop_table('audit_cycles')
    # ### end Alembic commands ###
